### ISSUE TITLE
Cannot install on Mac

### ISSUE THREAD

**Issue by prescod** [Dao-AILab/causal-conv1d#2]
```% pip --version
pip 23.3.1 from /private/tmp/mamba-chat/venv/lib/python3.11/site-packages/pip (python 3.11)

% pip install causal-conv1d
Collecting causal-conv1d
  Using cached causal_conv1d-1.0.0.tar.gz (6.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/private/tmp/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/private/tmp/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/tmp/mamba-chat/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5l/v33xmdnn2sx5lb2xpff6v4t40000gn/T/pip-build-env-gk93e613/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5l/v33xmdnn2sx5lb2xpff6v4t40000gn/T/pip-build-env-gk93e613/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5l/v33xmdnn2sx5lb2xpff6v4t40000gn/T/pip-build-env-gk93e613/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/5l/v33xmdnn2sx5lb2xpff6v4t40000gn/T/pip-build-env-gk93e613/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by marcusze** [comment]
same here..

**Comment by havietisov** [comment]
made a merge request with a fix

**Comment by havietisov** [comment]
I can't see *.toml project files in the original repo, so I just asked for a pull request with minimal changes. lets you install this at least from source. I also have no experience with *.toml. If you have ideas for improvements, I guess you're free to create pull requests!

**Comment by danstowell** [comment]
Just to comment that I also had this same problem. I'm on Ubuntu 22.04 using virtualenv. I already have `setuptools` (from apt). I was able to proceed a bit further by doing a few `pip install`s... but I'm not fully installed yet.

**Comment by plasma-vision** [comment]
I was able to resolve this by running $ pip install wheel
I think the packaging error is spurious.

**Comment by ajie220209** [comment]
> 听起来我知道问题出在哪里：您需要安装 setuptools 和 buildtools，然后才能安装它

Even though I have setuptools and buildtools installed, I still get an error when I run them.I think setuptools and buildtools are probably not the problem.
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Users\cwj\.conda\envs\vmunet\Lib\site-packages\causal-conv1d\setup.py:78: UserWarning: causal_conv1d was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/py
torch/pytorch, only images whose names contain 'devel' will provide nvcc.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\cwj\.conda\envs\vmunet\Lib\site-packages\causal-conv1d\setup.py", line 112, in <module>
          if bare_metal_version >= Version("11.8"):
      NameError: name 'bare_metal_version' is not defined
     
     
      torch.__version__  = 2.1.1+cu118
     
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ovo-Tim** [comment]
I can only folk the repository and build it locally
